import "./index.html";
import "./index.scss";
import "./components/header/animations";
import "./components/partners/animations";
import "./components/what-can/animations";
import "./components/our-feat/animations";
import "./components/setup/animations";
import "./components/integrate/animations";
const pow = (a, b) => a * b;
console.log(pow(2, 4));
